ODDLY_EXCHANGE="oddly.events"

VERIFY_ROUTING_KEY="registration.event.verify"
NOTIFICATION_ROUTING_KEY="notification.event.notify"

DEFAULT_PAGE_LIMIT = 20
DESCRIPTION_TRUNCATE_LENGTH = 100
VERIFICATION_CODE_CHARS = '0123456789'
VERIFICATION_CODE_LENGTH = 6